language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -i http://pypi.pediapress.com/simple/ mwlib
script:
# Running yamdwe itself is only to confirm the main program imports/runs correctly
# TODO: find a friendly Mediawiki that we can hammer part of an integration test!
  - ./yamdwe.py --help
  - ./wikicontent_tests.py
